### ISSUE TITLE
Index Lunr Search automatically after install?

### ISSUE THREAD

**Issue by gitressa** [drupal-tome/bookish#6]
**Describe the bug**
After installing Bookish, I get an "Access denied" message, if I click the "Search" link.

**To Reproduce**
1. Install Bookish
2. Click on 'Search' (https://tome-project.lndo.site/search)
3. See that you get a "**Access denied** You're not allowed to be here!" message
4. Go to `/admin/config/lunr_search/default` and click Index
5. Click on 'Search', and see that you now get a search field, and can search

**Suggested solution**
Maybe the Lunr Search index can be indexed automatically after installation, to prevent this?

**Comment by mortenson** [comment]
@gitressa Good idea - the only way to do this is to use `node`, or to redirect to a page which executes some JavaScript in the browser, which is kind of rough. So maybe a nice alternative would be to provide an user-who-can-index-only error message on that page.

**Comment by mortenson** [comment]
I've released a new version of Lunr that adds a message for admins prompting them to index with visiting `/search`.

Since Bookish/Lunr doesn't control the install process, and `node` isn't a requirement for running Drupal, I think I'm unlikely to fully automate building the search index on install. I'm thinking about clever solutions but don't have an idea I'm happy with yet, maybe I would accept a  PR/patch to Lunr but not sure what it would look like.

**Comment by gitressa** [comment]
@mortenson That's a perfectly fine work-around, which works well. Thanks! The important part is telling the user how the issue can be solved, so just having that message pop up will save users a lot of time.

And let me send a big Thank You in your direction for all the time and energy you have put into building Tome, Bookish, Lunr/Drupal integration, etc. I really appreciate it.
